### ISSUE TITLE
CSS doesn't support low resolutions

### ISSUE THREAD

**Issue by Oreolek** [halcyon-suite/halcyon#13]
CSS doesn't support 1024x768 monitors.

**Comment by nipos** [comment]
The three columns need more space than 1024 pixels.
I'll try to reduce it to two columns if there isn't enough space for three.
Smaller desktop screens will be supported then but for phones there will be an completely different and optimized user interface some time in the future.

**Comment by nipos** [comment]
As announced in our blog post,all Github issues are closed now!
We wrote all bugs to our to do list and will fix them in future releases without noting it here.
You can get new releases only from https://notabug.org/halcyon-suite/halcyon
Please do not open new issues here,use our new repository instead or write to us in the fediverse.
Our blog post: https://nikisoft.myblog.de/nikisoft/art/11626163/Our-move-from-Github-to-NotABug
