### ISSUE TITLE
Option to auto-pause gifs

### ISSUE THREAD

**Issue by averageunicorn** [halcyon-suite/halcyon#26]
On default mastodon, there is an option called "Auto-play animated GIFs" that you have to check if you want that to happen.

It would be cool to have some way to stop gifs from auto-playing in Halcyon, too. That option should include gif avatars.

**Comment by neetshin** [comment]
Thanks for reporting, this feature will be included in the next stable version.

<img width="718" alt="2018-01-28 14 09 22" src="https://user-images.githubusercontent.com/19276905/35480485-fb311c58-0434-11e8-9637-fa97d2438fc3.png">
