### ISSUE TITLE
Support for ActivityPub and other ActivityPub implementating servers?

### ISSUE THREAD

**Issue by poVoq** [halcyon-suite/halcyon#29]
Would be cool if this could become a general JS/PHP client for ActivityPub servers.

I am especially interested if it could be possible to use a Nextcloud backend, which already includes a lot of ActivityPub services, but is not yet geared towards federated microblogging.
See:
https://help.nextcloud.com/t/federated-microblogging-with-activitypub-api-nc12/

**Comment by neetshin** [comment]
Mastodon is running on ActivityPub based server from version 1.6.0
**ref:** https://github.com/tootsuite/mastodon/issues/1557

And Halcyon is just a front-end client, it fetches information from ActivityPub based server and show it in browser. There isn't matter, I guess.

If I misunderstood and it's still problem, please re-open this issue and then explain me where should I enhance/fix.

**Comment by nightpool** [comment]
@poVoq Mastodon does not implement the ActivityPub client-to-server API, only the activitypub server-to-server API. This means that clients don't use ActivityPub, only the server itself does.
