### ISSUE TITLE
Infinite Scroll is broken

### ISSUE THREAD

**Issue by nightpool** [halcyon-suite/halcyon#30]
Getting this error when trying to scroll on https://halcyon.cybre.space:

![image](https://user-images.githubusercontent.com/233815/32084061-01dd0cd6-ba95-11e7-9ecb-ef1e8b4146fd.png)

![image](https://user-images.githubusercontent.com/233815/32084067-0b2c295c-ba95-11e7-80f7-71293791871d.png)

Maybe an API compatibility problem? We're on 2.0.

**Comment by nipos** [comment]
For me infinite scroll works.
I had this problem for a long time but it was fixed with an Mastodon server update.
I can't remember which version it was but it still works.

**Comment by nightpool** [comment]
This is with mastodon version 2.0. It may be a result of the recent ID changes, or something else.

**Comment by nightpool** [comment]
for what it's worth, I'm strongly considering making halcyon my default client, and this issue is really stopping me from using it more then occasionally.

**Comment by nipos** [comment]
Yes,my instance uses Mastodon 2.0,too.
Halcyon is already my default client.
I have used it from my beginning with Mastodon and I love it.
If there were only the default Mastodon client,I would problably not use it anymore as it is so ugly and complicated.

**Comment by nightpool** [comment]
Nevermind, looks like this is a duplicate of #20. I found that our installation didn't have that fix in it.
