### ISSUE TITLE
[suggestion] Ctrl-V to paste images

### ISSUE THREAD

**Issue by nightpool** [halcyon-suite/halcyon#37]
I might implement this myself if I get time in the next week, but one of the things i'm missing a TON is the ability to upload images using ctrl-V. the Mastodon UI supports this now and so does twitter. I use a LOT of screenshots and it's really cumbersome to have to paste them, save them somewhere, go to halcyon, find my images, and upload them. a simple ctrl-v makes it *tons* easier to post.

**Comment by neetshin** [comment]
This feature will be included in the next version
