### ISSUE TITLE
old display name

### ISSUE THREAD

**Issue by nightpool** [halcyon-suite/halcyon#38]
on the front page, it shows my display name like this:

![image](https://user-images.githubusercontent.com/233815/32987706-1d65b078-ccc1-11e7-88ca-452d064b72a2.png)

but I changed my display name back from the "spooky" October display name weeks ago, and this is what it looks like now:
![image](https://user-images.githubusercontent.com/233815/32987709-2f8c5856-ccc1-11e7-8189-9762d67b149c.png)

this is **just** on the dashboard page

**Comment by neetshin** [comment]
Halcyon caches profile from `/api/v1/accounts/verify_credentials` for each session. So it update when restart your browser.
This problem will fix in next version

**Comment by neetshin** [comment]
This problem will be resolve in the next version
