### ISSUE TITLE
links seem to be cut off

### ISSUE THREAD

**Issue by tsia** [halcyon-suite/halcyon#7]
i just posted this toot: https://chaos.social/@tsia/99874804939347372
and on the mastodon web interface it looks like this:
![selection_003](https://user-images.githubusercontent.com/1386595/38870935-99b34ace-424f-11e8-82b0-ce5caf4c2f91.png)
on https://social.dev-wiki.de it looks like this:
![selection_004](https://user-images.githubusercontent.com/1386595/38870965-ab881518-424f-11e8-8143-5c85ce96b14d.png)

the link itself is working properly but it seems that the Ellipsis somehow gets lost

**Comment by nipos** [comment]
The problem is that the three dots are missing if an link is shortened,right?
I'll try to fix that with the next release.
And what I also see in that screenshot is that special domains aren't formatted to be easy to read.
Mastodon doesn't do it better but I think it would be nice anyway if Halcyon does it correctly so I'll have a look at that,too.

**Comment by tsia** [comment]
yes, that is exactly it.

there is a big discussion going on about those special IDN domains. i am not sure if it is a good idea to display them in their "nice" unicode form.

https://www.wordfence.com/blog/2017/04/chrome-firefox-unicode-phishing/

**Comment by nipos** [comment]
You're right,that can also be an security problem.
I think there can be an solution for displaying it in the nice form and also noticing the user that it's not an normal domain.
There are so many possibilities how to design that.
I'll create an poll how that should be implemented but I won't leave unicode domains unsupported at all and I also won't ignore your complaint.
It makes sense but there must be an nice and functional solution.

**Comment by tsia** [comment]
very good solution!

**Comment by nipos** [comment]
The poll is online,now waiting for participants: https://social.csswg.org/@halcyon/99875918255569919

**Comment by nipos** [comment]
The bug with the missing ... at the end of cut links has already been fixed since version 1.1.4.
For the better displaying of unicode domains,there aren't enough participants at the poll now so I still have to wait.

**Comment by nipos** [comment]
As announced in our blog post,all Github issues are closed now!
We wrote all bugs to our to do list and will fix them in future releases without noting it here.
You can get new releases only from https://notabug.org/halcyon-suite/halcyon
Please do not open new issues here,use our new repository instead or write to us in the fediverse.
Our blog post: https://nikisoft.myblog.de/nikisoft/art/11626163/Our-move-from-Github-to-NotABug
