### ISSUE TITLE
Images are missing with multiple images toots.

### ISSUE THREAD

**Issue by osapon** [halcyon-suite/halcyon#8]
Multiple images toot can not be done correctly.
I fixed it in my repository, but since I put multilingual support first, it is difficult to pull request.
It is a good idea to refer to these commits. 

https://github.com/osapon/halcyon/issues/5

**Comment by nipos** [comment]
Thank you very much for reporting that.
I knew that problem but I forgot it and so it wasn't on my todo list.
It's difficult to see which parts of that big diff are really the fix and what it just a rewrite of the original code but I'll try to make use of your fix.

**Comment by nipos** [comment]
As announced in our blog post,all Github issues are closed now!
We wrote all bugs to our to do list and will fix them in future releases without noting it here.
You can get new releases only from https://notabug.org/halcyon-suite/halcyon
Please do not open new issues here,use our new repository instead or write to us in the fediverse.
Our blog post: https://nikisoft.myblog.de/nikisoft/art/11626163/Our-move-from-Github-to-NotABug
